### ISSUE TITLE
How do I get the AOVs

### ISSUE THREAD

**Issue by Maxinger15** [DeclanRussell/NvidiaAIDenoiser#21]
Hello,
i am a bit confused about the AOVs. 
How can I get them? 
When I google it they are mentioned as boolean flags to set and then the filter is used but you mention it as
"path to input albedo/normal AOV."

Thank you in advance

**Comment by DeclanRussell** [comment]
Hey Max,
Your albedo and normal AOVs will typically be additional images that you point the tool towards. For example you may use the following command,
```
C:/Location of denoiser/Denoiser.exe -i C:/Location of image to be denoised/noiseyImage.exr -a C:/Location of albedo image/myalbedo.exr -n C:/Location of normal image/mynormal.exr -o C:/Location to save image/denoisedImage.exr
```
These images are of course optional but providing them should improve the quality of the denoising. The way you get these AOV images in the first place depends on the renderer you are using. Which renderer are you using? Perhaps I can point you in the right direction.

**Comment by Maxinger15** [comment]
I wanted to denoise images taken bei a camera and not some rendered images.

**Comment by DeclanRussell** [comment]
Ahh, unfortunately this tool is denoiser is designed for computer generated images rather than photos. It is not trained to recognize them kind of color noise you would encounter from photographs. This was also brought up in issue #9. I have had some success with monochrome images but you would probably be better off using a different solution like neat video or something.
